# Generated by Django 4.0.4 on 2022-05-02 10:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpagetag_blog_tags_blogpagetag_content_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='Full Title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('responsive_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_caption', wagtail.core.blocks.RichTextBlock(form_classname='caption', required=False))])), ('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.TextBlock()), ('page_link', wagtail.core.blocks.PageChooserBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
