# Generated by Django 4.0.4 on 2022-05-02 20:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='Full Title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('responsive_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_caption', wagtail.core.blocks.RichTextBlock(form_classname='caption', required=False))])), ('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.TextBlock()), ('page_link', wagtail.core.blocks.PageChooserBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code', wagtail.core.blocks.StructBlock([('Source_Code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('dart', 'Dart'), ('diff', 'diff'), ('django', 'Django/Jinja2'), ('docker', 'Docker'), ('git', 'Git'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'Javascript'), ('json', 'JSON'), ('kotlin', 'Kotlin'), ('markdown', 'Markdown'), ('powershell', 'PowerShell'), ('python', 'Python'), ('r', 'R'), ('jsx', 'React JSX'), ('tsx', 'React TSX'), ('regex', 'Regex'), ('smarty', 'Smarty'), ('solidity', 'Solidity (Ethereum)'), ('toml', 'TOML'), ('typescript', 'TypeScript'), ('scss', 'SCSS'), ('vim', 'vim'), ('wiki', 'Wiki markup'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], default_language='django', label='Source Code'))]))]),
        ),
    ]
