# Generated by Django 3.2.13 on 2022-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220626_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ColorScheme',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
