# Generated by Django 3.2.13 on 2022-06-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0003_homepage_colorscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
    ]
