# Generated by Django 4.0.4 on 2022-04-15 15:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_summary_homepage_hero_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Hero_Summary',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
