# Generated by Django 4.0.4 on 2022-05-02 10:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='Description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
