# Generated by Django 3.2.13 on 2022-06-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_alter_portfoliopage_my_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ColorScheme',
            field=models.IntegerField(blank=True, choices=[(1, 'Purple Blue'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D')], default=1),
        ),
    ]
