# Generated by Django 3.2.13 on 2022-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_project_colorscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ColorScheme',
            field=models.IntegerField(blank=True, choices=[(1, 'Purple Blue'), (2, 'Loan Money'), (3, 'Small Business'), (4, 'Fat Cat'), (5, 'Global Warming')], default=1),
        ),
    ]
